### ISSUE TITLE
I want Naija whot source code.

### ISSUE THREAD

**Issue by Sbilyamin01** [mykeels/whot#4]
Please i want Naija whot Source code, how can i get it please

**Comment by mykeels** [comment]
This is it. You are free to download and use it.

**Comment by Sbilyamin01** [comment]
> This is it. You are free to download and use it.

Sorry i couldn't see the link to download or anything, can you please give me your number to chat you up so you explain to me better.
Please Bro

**Comment by mykeels** [comment]
https://github.com/mykeels/whot/archive/refs/heads/master.zip
